version: "3"
services:
  node:
    build: 
      context: ./docker/node
      dockerfile: Dockerfile_node
    tty: true
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
      - "8080:8080"
    user: node
    command: sh -c "cd redux_todo && yarn start"
    depends_on:
      - mongo-db

  mongo-db:
    image: "mongo:3.6"
    ports:
      - "27017:27017"